name: Docker

on:
  push:
    branches: [ lczero ]
  pull_request:
    branches: [ lczero ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)